bagis:
  terrain: BAGIS_Reference_Maps.lyr
  dem10: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
  dem30: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
  preferredDem: dem30
  demElevUnit: Meters
  gaugeStation: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_USGS_ACTIVE/FeatureServer/0
  gaugeStationName: name
  gaugeStationArea: basinarea
  gaugeStationUnits: Square Mile
  snotel: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNTL_ACTIVE/FeatureServer/0
  snotelElev: elevation
  snotelName: name
  snowCourse: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNOW_ACTIVE/FeatureServer/0
  snowCourseElev: elevation
  snowCourseName: name
  prism: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1981_2010
  westernStateBoundaries: http://bagis.geog.pdx.edu/arcgis/rest/services/BAGIS_GISLayers/AOI_Location_Maps/MapServer

bagis-pro:
  dataSources:
    - layerType: Snotel SWE
      description: SWE Data Source - Averaged daily SNOw Data Assimilation System (SNODAS) Snow Water Equivalent (SWE) from 2004 to current water year data. See https://www.nohrsc.noaa.gov/ for more information
      uri: http://bagis.geog.pdx.edu/arcgis/services/DAILY_SWE_NORMALS/
      units: Millimeters
    - layerType: Precipitation
      description: 30-year (1991-2020) monthly/quarterly/annual average precipitation data created by the PRISM Climate Group
      uri: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/
      units: Inches
    - layerType: SNOTEL
      description: Active SNOTEL sites
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNTL_ACTIVE/FeatureServer/0
    - layerType: Snow Course
      description: Active Snow Course stations
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNOW_ACTIVE/FeatureServer/0
    - layerType: Roads
      description: Sample USFS roads for BAGIS-PRO development
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/Sample_Forest_Service_Roads/FeatureServer/0
    - layerType: Public Land
      description: Federal land GIS layer, used as an input for SNOTEL site selection model in BAGIS
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/BAGIS_Public_Land/FeatureServer/0
    - layerType: Vegetation Type
      description: 30-meter Landfire Existing Vegetation Type with additional attributes of intcp_snow, intcp_srain, intcp_wrain, and root_depth
      uri: http://bagis.geog.pdx.edu/arcgis/rest/services/BAGIS_Databin/LF_us_140evt/ImageServer
    - layerType: Land Cover
      description: 2019 30-meter NLCD Land Cover
      uri: http://bagis.geog.pdx.edu/arcgis/rest/services/BAGIS_Databin/NLCD_2019_land_cover/ImageServer
 

  BatchSettings:
     EBagisServer: https://ebagis.geog.pdx.edu
     SweDisplayUnits: Inches
     DemUnits: Meters
     DefaultDemInterval: 1000
     DemDisplayUnits: Feet
     AoiPrecipFile: prism.gdb\Annual
     PrecipZonesCount: 8
     AspectDirectionsCount: 4
     MinElevationZonesCount: 8
     SnotelSweZonesCount: 7
     PrecipBufferDistance: 1000
     PrecipBufferUnits: Meters
     SnotelBufferDistance: 5
     SnotelBufferUnits: Kilometers
     RoadsAnalysisBufferDistance: 300
     RoadsAnalysisBufferUnits: Feet
     Publisher: nwcc_nrcs
     SiteElevRangeFeet: 500
     SiteBufferDistMiles: 5.642
     CriticalPrecipMinMeanVolInches: 20.0
     CriticalPrecipTotalMaxVolPct: 66.6
     AnnualRunoffItemId: f641bbacceff4c1bb3f9661bd8f9de8d
     NLCDLandCoverLayerItemId: 9f61719bc5314247bda76469362c7554
     AnnualRunoffDataDescr: Basin Average Annual Naturalized Runoff Volume (1991-2020)
     AnnualRunoffDataYear: 2022
     AnnualRunoffDataField: Average_kac_ft_1991_2020
     PrecipContribZones: 9
     MasterAoiList: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/master_aoi_list_fs/FeatureServer
     PdfExportResolution: 300
     Version: 1.0

bagis-p:
  datasources:
    - id: 4
      name: JH_Coef_Aug_Tmax
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmax_august/ImageServer
      description: August Max Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Aug_Tmax
    - id: 5
      name: JH_Coef_Aug_Tmin
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmin_august/ImageServer 
      description: August Min Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Aug_Tmin
    - id: 6
      name: JH_Coef_Jul_Tmin
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmin_july/ImageServer 
      description: July Min Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Jul_Tmin
    - id: 7
      name: JH_Coef_Jul_Tmax
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmax_july/ImageServer 
      description: July Max Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Jul_Tmax
    - id: 8
      name: Landfire_CC
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/LF_us_130cc/ImageServer 
      description: Landfire_CC, cover density for tree type. This cover density layer is used only for the estimation of rad_trncf parameter.
    - id: 9
      name: Landfire_EVC_CC
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/LF_us_130evc_cc/ImageServer 
      description: Cover Density from Landfire EVC layer. This layer includes cover density for all vegetation types (trees, grass, shrub)
    - id: 10
      name: Landfire_EVT
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/LF_us_140evt/ImageServer 
      description: Landfire Existing Vegetation 
    - id: 11
      name: NLCD_Impervious
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/NLCD_2019_impervious/ImageServer 
      description: NLCD % Impervious
    - id: 12
      name: Soil
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/STATSGO_BAGIS_muid/ImageServer 
      description: Soil
    - id: 13
      name: Soil_Texture
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/STATSGO_BAGIS_texture/ImageServer 
      description: Soil_Texture

bagis-h: []