bagis:
  terrain: BAGIS_Reference_Maps.lyr
  dem10: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
  dem30: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
  preferredDem: dem30
  demElevUnit: Meters
  gaugeStation: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_USGS_ACTIVE/FeatureServer/0
  gaugeStationName: name
  gaugeStationArea: basinarea
  gaugeStationUnits: Square Mile
  snotel: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNTL_ACTIVE/FeatureServer/0
  snotelElev: elevation
  snotelName: name
  snowCourse: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNOW_ACTIVE/FeatureServer/0
  snowCourseElev: elevation
  snowCourseName: name
  prism: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1981_2010
  westernStateBoundaries: http://bagis.geog.pdx.edu/arcgis/rest/services/BAGIS_GISLayers/AOI_Location_Maps/MapServer

bagis-pro:
  dataSources:
    - layerType: Snotel SWE
      heading: Snow Water Equivalent (SWE)
      description: SWE Data Source - Averaged daily SNOw Data Assimilation System (SNODAS) Snow Water Equivalent (SWE) from 2004 to current water year data. See https://www.nohrsc.noaa.gov/ for more information.
      uri: http://bagis.geog.pdx.edu/arcgis/services/DAILY_SWE_NORMALS/
      units: Millimeters
    - layerType: Precipitation
      heading: Precipitation
      description: 30-year (1991-2020) monthly/quarterly/annual average precipitation data created by the PRISM Climate Group. See https://prism.oregonstate.edu/ for more information.
      uri: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/
      units: Inches
    - layerType: SNOTEL
      heading: Active SNOTEL sites
      description: Active SNOTEL sites data hosted on Natural Resources Conservation Service (NRCS) National Water and Climate Center (NWCC) Air and Water Database (AWDB). See https://www.nrcs.usda.gov/wps/portal/wcc/home/dataAccessHelp/webService/webServiceTutorial/ for more information.
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNTL_ACTIVE/FeatureServer/0
    - layerType: Snow Course
      heading: Active Snow Course sites
      description: Active Snow Course sites hosted on Natural Resources Conservation Service (NRCS) National Water and Climate Center (NWCC) Air and Water Database (AWDB). See https://www.nrcs.usda.gov/wps/portal/wcc/home/dataAccessHelp/webService/webServiceTutorial/ for more information.
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/stations_SNOW_ACTIVE/FeatureServer/0
    - layerType: SNOLITE
      heading: Active SNOLITE sites
      description: Active SNOLITE sites hosted on Natural Resources Conservation Service (NRCS) National Water and Climate Center (NWCC) Air and Water Database (AWDB). See https://www.nrcs.usda.gov/wps/portal/wcc/home/dataAccessHelp/webService/webServiceTutorial/ for more information.
      uri: http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_SNTLT_ACTIVE/FeatureServer/0
    - layerType: Snow Pillow
      heading: Active Snow Pillow sites
      description: Active Snow Pillow sites hosted on Natural Resources Conservation Service (NRCS) National Water and Climate Center (NWCC) Air and Water Database (AWDB). See https://www.nrcs.usda.gov/wps/portal/wcc/home/dataAccessHelp/webService/webServiceTutorial/ for more information.
      uri: http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_MSNT_ACTIVE/FeatureServer/0
    - layerType: Roads
      heading: Access Roads – for Potential Site Location Analysis
      description: USFS FSTopo Transportation Line 2020 version. See https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FSTopo_Transport_LN.xml for more information.
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/USFS_FSTopo_Transport_LN/FeatureServer/0
    - layerType: Land Ownership
      heading: Public Land Ownership – for Potential Site Location Analysis
      description: Federal non-wilderness and tribal land data based on the 2020 USGS Protected Areas Data (PAD) version 2.1. See https://www.usgs.gov/programs/gap-analysis-project/science/pad-us-data-overview for more information.
      uri: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/Public_and_Tribal_Lands/FeatureServer/0
    - layerType: Land Cover
      heading: Land Cover – for Potential Site Location Analysis
      description: 2019 NLCD Land Cover. See https://www.mrlc.gov for more information.
      uri: http://bagis.geog.pdx.edu/arcgis/rest/services/BAGIS_Databin/NLCD_2019_land_cover/ImageServer
 

  BatchSettings:
     EBagisServer: https://ebagis.geog.pdx.edu
     SweDisplayUnits: Inches
     DemUnits: Meters
     DefaultDemInterval: 1000
     DemDisplayUnits: Feet
     AoiPrecipFile: prism.gdb\Annual
     PrecipZonesCount: 8
     AspectDirectionsCount: 4
     MinElevationZonesCount: 8
     SnotelSweZonesCount: 7
     PrecipBufferDistance: 1000
     PrecipBufferUnits: Meters
     SnotelBufferDistance: 5
     SnotelBufferUnits: Kilometers
     RoadsAnalysisBufferDistance: 300
     RoadsAnalysisBufferUnits: Feet
     Publisher: nwcc_nrcs
     SiteElevRangeFeet: 500
     SiteBufferDistMiles: 5.642
     CriticalPrecipMinMeanVolInches: 20.0
     CriticalPrecipTotalMaxVolPct: 66.6
     AnnualRunoffItemId: f641bbacceff4c1bb3f9661bd8f9de8d
     NLCDLandCoverLayerItemId: 9f61719bc5314247bda76469362c7554
     AnnualRunoffDataDescr: Average Annual Naturalized Runoff Volume (1991-2020) data retrieved from Natural Resources Conservation Service (NRCS) National Water and Climate Center (NWCC) Air and Water Database (AWDB) by NWCC in 2022.
     AnnualRunoffDataField: Average_kac_ft_1991_2020
     PrecipContribZones: 9
     MasterAoiList: https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/master_aoi_list_fs/FeatureServer
     PdfExportResolution: 300
     SnodasSweLayoutItemId: 5de950a654b14c849a25a08b3b3a9bfd
     SnodasDeltaLayoutItemId: 1eafb8ca4b2048a2a22598d6372cf0d5
     SeasonalPrecipLayoutItemId: 34a1c22f75254c56918c5eb820a6810a
     PublicAndTribalLandsLayerItemId: c72cf8608c644a8c90c651e1bbfe815f
     MaximumSitesAllowed: 50
     Version: 2.0

bagis-p:
  datasources:
    - id: 4
      name: JH_Coef_Aug_Tmax
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmax_august/ImageServer
      description: August Max Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Aug_Tmax
    - id: 5
      name: JH_Coef_Aug_Tmin
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmin_august/ImageServer 
      description: August Min Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Aug_Tmin
    - id: 6
      name: JH_Coef_Jul_Tmin
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmin_july/ImageServer 
      description: July Min Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Jul_Tmin
    - id: 7
      name: JH_Coef_Jul_Tmax
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1991_2020_tmax_july/ImageServer 
      description: July Max Temperature for JH_Coef estimation
      jhCoeff: JH_Coef_Jul_Tmax
    - id: 8
      name: Landfire_CC
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/LF_us_130cc/ImageServer 
      description: Landfire_CC, cover density for tree type. This cover density layer is used only for the estimation of rad_trncf parameter.
    - id: 9
      name: Landfire_EVC_CC
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/LF_us_130evc_cc/ImageServer 
      description: Cover Density from Landfire EVC layer. This layer includes cover density for all vegetation types (trees, grass, shrub)
    - id: 10
      name: Landfire_EVT
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/LF_us_140evt/ImageServer 
      description: Landfire Existing Vegetation 
    - id: 11
      name: NLCD_Impervious
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/NLCD_2019_impervious/ImageServer 
      description: NLCD % Impervious
    - id: 12
      name: Soil
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/STATSGO_BAGIS_muid/ImageServer 
      description: Soil
    - id: 13
      name: Soil_Texture
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/STATSGO_BAGIS_texture/ImageServer 
      description: Soil_Texture

bagis-h: []